### ISSUE TITLE
Error converting nested lists

### ISSUE THREAD

**Issue by burck1** [kvz/json2hcl#11]
I ran into an issue converting a list of lists. I was converting [terraform-aws-vpn-gateway complete-dual-vpn-gateway example](https://github.com/terraform-aws-modules/terraform-aws-vpn-gateway/blob/0b73ee997145080468f2f3d60ee846739f71f87e/examples/complete-dual-vpn-gateway/main.tf#L58) to `json` and ran into the message `unable to parse HCL: At 58:74: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACK`.

Here is a simplified example outlining the problem. A _forward_ conversion produces no output.
```sh
$ json2hcl << EOM
{
  "locals": [
    {
      "public_subnets": [
        [
          "10.10.11.0/24",
          "10.10.12.0/24",
          "10.10.13.0/24"
        ]
      ]
    }
  ]
}
EOM
```

and a _reverse_ conversion produces an error.
```sh
$ json2hcl -reverse << EOM
locals {
  public_subnets = [["10.10.11.0/24", "10.10.12.0/24", "10.10.13.0/24"]]
}
EOM
unable to parse HCL: At 2:72: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACK
```

_My system info:_
```sh
$ json2hcl -version 
v0.0.6
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
$ uname -mrps
Darwin 18.2.0 x86_64 i386
```

**Comment by Acconut** [comment]
Thank you very much for bringing this to our attention. However, I am very sorry to say that I currently don't have the time to look into your problem. I hope someone else can step up and assist you.
