### ISSUE TITLE
fatal error: runtime: bsdthread_register error

### ISSUE THREAD

**Issue by bessyG** [kvz/json2hcl#19]
execution of json2hcl shows error 
```
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x126b3b, 0x21)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:566 +0x95 fp=0x7ff7bfeffa90 sp=0x7ff7bfeffa70
runtime.goenvs()
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/os_darwin.go:88 +0xa0 fp=0x7ff7bfeffac0 sp=0x7ff7bfeffa90
runtime.schedinit()
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/proc.go:450 +0x9c fp=0x7ff7bfeffb00 sp=0x7ff7bfeffac0
runtime.rt0_go(0x7ff7bfeffb30, 0x1, 0x7ff7bfeffb30, 0x1000, 0x1, 0x7ff7bfeffc70, 0x0, 0x7ff7bfeffc79, 0x7ff7bfeffc87, 0x7ff7bfeffc9b, ...)
	/home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/asm_amd64.s:145 +0x14f fp=0x7ff7bfeffb08 sp=0x7ff7bfeffb00
```

My system is Mac 12.0..1

**Comment by Acconut** [comment]
We don't use json2hcl anymore ourselves, so we can't invest time into it. However, this error looks like what is described in https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue. So if you compile json2hcl with a recent Go version on your own, you should be fine.

**Comment by rsun-thoughtworks** [comment]
> We don't use json2hcl anymore ourselves, so we can't invest time into it. However, this error looks like what is described in https://github.com/golang/go/wiki/MacOS12BSDThreadRegisterIssue. So if you compile json2hcl with a recent Go version on your own, you should be fine.

Not sure if you can share the alternative? Or you just no longer have the need to do the transform from json to terraform？

Thank you.

**Comment by Acconut** [comment]
> Or you just no longer have the need to do the transform from json to terraform？

We don't. But you can install a recent version of Go and compile json2hcl on your own using the instructions as https://github.com/kvz/json2hcl#development. Then it might work again.

**Comment by rsun-thoughtworks** [comment]
> > Or you just no longer have the need to do the transform from json to terraform？
> 
> We don't. But you can install a recent version of Go and compile json2hcl on your own using the instructions as https://github.com/kvz/json2hcl#development. Then it might work again.

Thank you for this project.

Wandering if you can trigger the pipeline, because the new build will be uploaded to Github release automatically.

**Comment by Acconut** [comment]
Maybe it works. https://github.com/kvz/json2hcl/releases/tag/v0.0.7

**Comment by greatbody** [comment]
> Maybe it works. https://github.com/kvz/json2hcl/releases/tag/v0.0.7

I have made a PR, pleasure if you can review.

**Comment by greatbody** [comment]
> Maybe it works. https://github.com/kvz/json2hcl/releases/tag/v0.0.7

No sure if you can help approve the PR?

**Comment by greatbody** [comment]
@Acconut Hi, not sure if you can help view my PR.

All the best.

**Comment by Acconut** [comment]
Should be fixed in https://github.com/kvz/json2hcl/releases/tag/v0.1.1
