### ISSUE TITLE
Latest release is missing artefacts

### ISSUE THREAD

**Issue by mbevc1** [kvz/json2hcl#20]
Could we cut another release containing build artefacts as well please?

**Comment by greatbody** [comment]
You may want to see my fork https://github.com/great-fork/json2hcl

**Comment by Acconut** [comment]
Will be fixed by https://github.com/kvz/json2hcl/pull/21

**Comment by Acconut** [comment]
Done in https://github.com/kvz/json2hcl/releases/tag/v0.1.1

**Comment by mbevc1** [comment]
Thanks :tada:
